package com.documenteditor.visitor;

import com.documenteditor.model.*;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Simple PDF-like export using plain text format.
 * This is a lightweight alternative that doesn't require external libraries.
 * For production use, this would be replaced with iText-based PDFExportVisitor.
 */
public class SimplePDFExportVisitor implements Visitor {
    private StringBuilder content;
    private String outputPath;
    
    public SimplePDFExportVisitor(String outputPath) {
        this.outputPath = outputPath;
        this.content = new StringBuilder();
    }
    
    @Override
    public void visitDocument(Document document) {
        // PDF-style header
        content.append("╔══════════════════════════════════════════════════════════════╗\n");
        content.append("║                    PDF DOCUMENT EXPORT                        ║\n");
        content.append("╚══════════════════════════════════════════════════════════════╝\n\n");
        
        // Document title (centered and bold)
        String title = document.getTitle();
        int padding = (60 - title.length()) / 2;
        content.append(" ".repeat(Math.max(0, padding)));
        content.append("【 ").append(title.toUpperCase()).append(" 】\n\n");
        content.append("─".repeat(64)).append("\n\n");
        
        // Visit all child elements
        for (DocumentElement element : document.getChildren()) {
            element.accept(this);
        }
        
        // PDF-style footer
        content.append("\n").append("─".repeat(64)).append("\n");
        content.append("Generated by Document Editor - PDF Export\n");
        content.append("═".repeat(64)).append("\n");
    }
    
    @Override
    public void visitParagraph(Paragraph paragraph) {
        // Justify text for PDF-like appearance
        String text = paragraph.getText();
        String[] words = text.split("\\s+");
        StringBuilder line = new StringBuilder();
        int lineWidth = 64;
        
        for (String word : words) {
            if (line.length() + word.length() + 1 > lineWidth) {
                content.append(line.toString().trim()).append("\n");
                line = new StringBuilder();
            }
            line.append(word).append(" ");
        }
        if (line.length() > 0) {
            content.append(line.toString().trim()).append("\n");
        }
        content.append("\n");
    }
    
    @Override
    public void visitHeadline(Headline headline) {
        int level = headline.getLevel();
        String marker = switch (level) {
            case 1 -> "═══";
            case 2 -> "───";
            case 3 -> "···";
            default -> "   ";
        };
        
        content.append("\n").append(marker).append(" ");
        content.append(headline.getText().toUpperCase());
        content.append(" ").append(marker).append("\n\n");
    }
    
    @Override
    public void visitImage(Image image) {
        content.append("┌").append("─".repeat(62)).append("┐\n");
        content.append("│ [IMAGE]                                                        │\n");
        content.append("│ File: ").append(String.format("%-54s", image.getFilename())).append(" │\n");
        content.append("│ Dimensions: ").append(String.format("%-48s", 
            image.getWidth() + "x" + image.getHeight() + " pixels")).append(" │\n");
        content.append("└").append("─".repeat(62)).append("┘\n\n");
    }
    
    /**
     * Write the PDF content to file and close.
     */
    public void close() throws IOException {
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputPath))) {
            writer.write(content.toString());
        }
    }
    
    public String getOutputPath() {
        return outputPath;
    }
    
    public String getContent() {
        return content.toString();
    }
}
